# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Networking/Responses/PlayerUpdateResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Map.Fort import FortData_pb2 as Map_dot_Fort_dot_FortData__pb2
Enums_dot_PokemonId__pb2 = Map_dot_Fort_dot_FortData__pb2.Enums_dot_PokemonId__pb2
Enums_dot_TeamColor__pb2 = Map_dot_Fort_dot_FortData__pb2.Enums_dot_TeamColor__pb2
Map_dot_Fort_dot_FortType__pb2 = Map_dot_Fort_dot_FortData__pb2.Map_dot_Fort_dot_FortType__pb2
Map_dot_Fort_dot_FortSponsor__pb2 = Map_dot_Fort_dot_FortData__pb2.Map_dot_Fort_dot_FortSponsor__pb2
Map_dot_Fort_dot_FortRenderingType__pb2 = Map_dot_Fort_dot_FortData__pb2.Map_dot_Fort_dot_FortRenderingType__pb2
Map_dot_Fort_dot_FortLureInfo__pb2 = Map_dot_Fort_dot_FortData__pb2.Map_dot_Fort_dot_FortLureInfo__pb2
Enums_dot_PokemonId__pb2 = Map_dot_Fort_dot_FortData__pb2.Enums_dot_PokemonId__pb2
from Map.Pokemon import WildPokemon_pb2 as Map_dot_Pokemon_dot_WildPokemon__pb2
Data_dot_PokemonData__pb2 = Map_dot_Pokemon_dot_WildPokemon__pb2.Data_dot_PokemonData__pb2
Enums_dot_PokemonId__pb2 = Map_dot_Pokemon_dot_WildPokemon__pb2.Enums_dot_PokemonId__pb2
Enums_dot_PokemonMove__pb2 = Map_dot_Pokemon_dot_WildPokemon__pb2.Enums_dot_PokemonMove__pb2

from Map.Fort.FortData_pb2 import *
from Map.Pokemon.WildPokemon_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Networking/Responses/PlayerUpdateResponse.proto',
  package='POGOProtos.Networking.Responses',
  syntax='proto3',
  serialized_pb=_b('\n/Networking/Responses/PlayerUpdateResponse.proto\x12\x1fPOGOProtos.Networking.Responses\x1a\x17Map/Fort/FortData.proto\x1a\x1dMap/Pokemon/WildPokemon.proto\"\x96\x01\n\x14PlayerUpdateResponse\x12:\n\rwild_pokemons\x18\x01 \x03(\x0b\x32#.POGOProtos.Map.Pokemon.WildPokemon\x12,\n\x05\x66orts\x18\x02 \x03(\x0b\x32\x1d.POGOProtos.Map.Fort.FortData\x12\x14\n\x0c\x66orts_nearby\x18\x03 \x01(\x05P\x00P\x01\x62\x06proto3')
  ,
  dependencies=[Map_dot_Fort_dot_FortData__pb2.DESCRIPTOR,Map_dot_Pokemon_dot_WildPokemon__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PLAYERUPDATERESPONSE = _descriptor.Descriptor(
  name='PlayerUpdateResponse',
  full_name='POGOProtos.Networking.Responses.PlayerUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wild_pokemons', full_name='POGOProtos.Networking.Responses.PlayerUpdateResponse.wild_pokemons', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='forts', full_name='POGOProtos.Networking.Responses.PlayerUpdateResponse.forts', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='forts_nearby', full_name='POGOProtos.Networking.Responses.PlayerUpdateResponse.forts_nearby', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=291,
)

_PLAYERUPDATERESPONSE.fields_by_name['wild_pokemons'].message_type = Map_dot_Pokemon_dot_WildPokemon__pb2._WILDPOKEMON
_PLAYERUPDATERESPONSE.fields_by_name['forts'].message_type = Map_dot_Fort_dot_FortData__pb2._FORTDATA
DESCRIPTOR.message_types_by_name['PlayerUpdateResponse'] = _PLAYERUPDATERESPONSE

PlayerUpdateResponse = _reflection.GeneratedProtocolMessageType('PlayerUpdateResponse', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERUPDATERESPONSE,
  __module__ = 'Networking.Responses.PlayerUpdateResponse_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Responses.PlayerUpdateResponse)
  ))
_sym_db.RegisterMessage(PlayerUpdateResponse)


# @@protoc_insertion_point(module_scope)
