# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Networking/Responses/UseItemReviveResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Networking/Responses/UseItemReviveResponse.proto',
  package='POGOProtos.Networking.Responses',
  syntax='proto3',
  serialized_pb=_b('\n0Networking/Responses/UseItemReviveResponse.proto\x12\x1fPOGOProtos.Networking.Responses\"\xe5\x01\n\x17UseRevivePotionResponse\x12O\n\x06result\x18\x01 \x01(\x0e\x32?.POGOProtos.Networking.Responses.UseRevivePotionResponse.Result\x12\x0f\n\x07stamina\x18\x02 \x01(\x05\"h\n\x06Result\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x14\n\x10\x45RROR_NO_POKEMON\x10\x02\x12\x14\n\x10\x45RROR_CANNOT_USE\x10\x03\x12\x1a\n\x16\x45RROR_DEPLOYED_TO_FORT\x10\x04\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_USEREVIVEPOTIONRESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='POGOProtos.Networking.Responses.UseRevivePotionResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_NO_POKEMON', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_CANNOT_USE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_DEPLOYED_TO_FORT', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=211,
  serialized_end=315,
)
_sym_db.RegisterEnumDescriptor(_USEREVIVEPOTIONRESPONSE_RESULT)


_USEREVIVEPOTIONRESPONSE = _descriptor.Descriptor(
  name='UseRevivePotionResponse',
  full_name='POGOProtos.Networking.Responses.UseRevivePotionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='POGOProtos.Networking.Responses.UseRevivePotionResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stamina', full_name='POGOProtos.Networking.Responses.UseRevivePotionResponse.stamina', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _USEREVIVEPOTIONRESPONSE_RESULT,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=315,
)

_USEREVIVEPOTIONRESPONSE.fields_by_name['result'].enum_type = _USEREVIVEPOTIONRESPONSE_RESULT
_USEREVIVEPOTIONRESPONSE_RESULT.containing_type = _USEREVIVEPOTIONRESPONSE
DESCRIPTOR.message_types_by_name['UseRevivePotionResponse'] = _USEREVIVEPOTIONRESPONSE

UseRevivePotionResponse = _reflection.GeneratedProtocolMessageType('UseRevivePotionResponse', (_message.Message,), dict(
  DESCRIPTOR = _USEREVIVEPOTIONRESPONSE,
  __module__ = 'Networking.Responses.UseItemReviveResponse_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Responses.UseRevivePotionResponse)
  ))
_sym_db.RegisterMessage(UseRevivePotionResponse)


# @@protoc_insertion_point(module_scope)
