# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request.proto',
  package='',
  serialized_pb='\n\rrequest.proto\"\xca\x04\n\x07Request\x12\x1b\n\x04type\x18\x01 \x02(\x0e\x32\r.Request.Type\x12\x0e\n\x06rpc_id\x18\x03 \x01(\x03\x12!\n\x07payload\x18\x04 \x03(\x0b\x32\x10.Request.Payload\x12#\n\x08unknown6\x18\x06 \x01(\x0b\x32\x11.Request.Unknown6\x12\x10\n\x08latitude\x18\x07 \x01(\x06\x12\x11\n\tlongitude\x18\x08 \x01(\x06\x12\x10\n\x08\x61ltitude\x18\t \x01(\x06\x12\x1f\n\x04\x61uth\x18\n \x01(\x0b\x32\x11.Request.AuthInfo\x12\x11\n\tunknown12\x18\x0c \x01(\x03\x1aZ\n\x07Payload\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.Request.Payload.Type\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x1c\n\x04Type\x12\x14\n\x10REQUEST_ENDPOINT\x10\x02\x1ah\n\x08Unknown6\x12\x10\n\x08unknown1\x18\x01 \x02(\x05\x12,\n\x08unknown2\x18\x02 \x02(\x0b\x32\x1a.Request.Unknown6.Unknown2\x1a\x1c\n\x08Unknown2\x12\x10\n\x08unknown1\x18\x01 \x02(\x0c\x1an\n\x08\x41uthInfo\x12\x10\n\x08provider\x18\x01 \x02(\t\x12$\n\x05token\x18\x02 \x02(\x0b\x32\x15.Request.AuthInfo.JWT\x1a*\n\x03JWT\x12\x10\n\x08\x63ontents\x18\x01 \x02(\t\x12\x11\n\tunknown13\x18\x02 \x02(\x05\")\n\x04Type\x12\x14\n\x10REQUEST_ENDPOINT\x10\x02\x12\x07\n\x03TWO\x10\x02\x1a\x02\x10\x01')



_REQUEST_PAYLOAD_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='Request.Payload.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REQUEST_ENDPOINT', index=0, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=315,
  serialized_end=343,
)

_REQUEST_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='Request.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REQUEST_ENDPOINT', index=0, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TWO', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=_descriptor._ParseOptions(descriptor_pb2.EnumOptions(), '\020\001'),
  serialized_start=563,
  serialized_end=604,
)


_REQUEST_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='Request.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Request.Payload.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='Request.Payload.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_PAYLOAD_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=253,
  serialized_end=343,
)

_REQUEST_UNKNOWN6_UNKNOWN2 = _descriptor.Descriptor(
  name='Unknown2',
  full_name='Request.Unknown6.Unknown2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unknown1', full_name='Request.Unknown6.Unknown2.unknown1', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=421,
  serialized_end=449,
)

_REQUEST_UNKNOWN6 = _descriptor.Descriptor(
  name='Unknown6',
  full_name='Request.Unknown6',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unknown1', full_name='Request.Unknown6.unknown1', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown2', full_name='Request.Unknown6.unknown2', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_UNKNOWN6_UNKNOWN2, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=345,
  serialized_end=449,
)

_REQUEST_AUTHINFO_JWT = _descriptor.Descriptor(
  name='JWT',
  full_name='Request.AuthInfo.JWT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contents', full_name='Request.AuthInfo.JWT.contents', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown13', full_name='Request.AuthInfo.JWT.unknown13', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=519,
  serialized_end=561,
)

_REQUEST_AUTHINFO = _descriptor.Descriptor(
  name='AuthInfo',
  full_name='Request.AuthInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='provider', full_name='Request.AuthInfo.provider', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='Request.AuthInfo.token', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_AUTHINFO_JWT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=451,
  serialized_end=561,
)

_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Request.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rpc_id', full_name='Request.rpc_id', index=1,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='Request.payload', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown6', full_name='Request.unknown6', index=3,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Request.latitude', index=4,
      number=7, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Request.longitude', index=5,
      number=8, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='Request.altitude', index=6,
      number=9, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auth', full_name='Request.auth', index=7,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown12', full_name='Request.unknown12', index=8,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_PAYLOAD, _REQUEST_UNKNOWN6, _REQUEST_AUTHINFO, ],
  enum_types=[
    _REQUEST_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=604,
)

_REQUEST_PAYLOAD.fields_by_name['type'].enum_type = _REQUEST_PAYLOAD_TYPE
_REQUEST_PAYLOAD.containing_type = _REQUEST;
_REQUEST_PAYLOAD_TYPE.containing_type = _REQUEST_PAYLOAD;
_REQUEST_UNKNOWN6_UNKNOWN2.containing_type = _REQUEST_UNKNOWN6;
_REQUEST_UNKNOWN6.fields_by_name['unknown2'].message_type = _REQUEST_UNKNOWN6_UNKNOWN2
_REQUEST_UNKNOWN6.containing_type = _REQUEST;
_REQUEST_AUTHINFO_JWT.containing_type = _REQUEST_AUTHINFO;
_REQUEST_AUTHINFO.fields_by_name['token'].message_type = _REQUEST_AUTHINFO_JWT
_REQUEST_AUTHINFO.containing_type = _REQUEST;
_REQUEST.fields_by_name['type'].enum_type = _REQUEST_TYPE
_REQUEST.fields_by_name['payload'].message_type = _REQUEST_PAYLOAD
_REQUEST.fields_by_name['unknown6'].message_type = _REQUEST_UNKNOWN6
_REQUEST.fields_by_name['auth'].message_type = _REQUEST_AUTHINFO
_REQUEST_TYPE.containing_type = _REQUEST;
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST

class Request(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Payload(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _REQUEST_PAYLOAD

    # @@protoc_insertion_point(class_scope:Request.Payload)

  class Unknown6(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType

    class Unknown2(_message.Message):
      __metaclass__ = _reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _REQUEST_UNKNOWN6_UNKNOWN2

      # @@protoc_insertion_point(class_scope:Request.Unknown6.Unknown2)
    DESCRIPTOR = _REQUEST_UNKNOWN6

    # @@protoc_insertion_point(class_scope:Request.Unknown6)

  class AuthInfo(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType

    class JWT(_message.Message):
      __metaclass__ = _reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _REQUEST_AUTHINFO_JWT

      # @@protoc_insertion_point(class_scope:Request.AuthInfo.JWT)
    DESCRIPTOR = _REQUEST_AUTHINFO

    # @@protoc_insertion_point(class_scope:Request.AuthInfo)
  DESCRIPTOR = _REQUEST

  # @@protoc_insertion_point(class_scope:Request)


_REQUEST_TYPE.has_options = True
_REQUEST_TYPE._options = _descriptor._ParseOptions(descriptor_pb2.EnumOptions(), '\020\001')
# @@protoc_insertion_point(module_scope)
