# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Map/Fort/FortData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Enums import PokemonId_pb2 as Enums_dot_PokemonId__pb2
from Enums import TeamColor_pb2 as Enums_dot_TeamColor__pb2
from Map.Fort import FortType_pb2 as Map_dot_Fort_dot_FortType__pb2
from Map.Fort import FortSponsor_pb2 as Map_dot_Fort_dot_FortSponsor__pb2
from Map.Fort import FortRenderingType_pb2 as Map_dot_Fort_dot_FortRenderingType__pb2
from Map.Fort import FortLureInfo_pb2 as Map_dot_Fort_dot_FortLureInfo__pb2
Enums_dot_PokemonId__pb2 = Map_dot_Fort_dot_FortLureInfo__pb2.Enums_dot_PokemonId__pb2

from Enums.PokemonId_pb2 import *
from Enums.TeamColor_pb2 import *
from Map.Fort.FortType_pb2 import *
from Map.Fort.FortSponsor_pb2 import *
from Map.Fort.FortRenderingType_pb2 import *
from Map.Fort.FortLureInfo_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Map/Fort/FortData.proto',
  package='POGOProtos.Map.Fort',
  syntax='proto3',
  serialized_pb=_b('\n\x17Map/Fort/FortData.proto\x12\x13POGOProtos.Map.Fort\x1a\x15\x45nums/PokemonId.proto\x1a\x15\x45nums/TeamColor.proto\x1a\x17Map/Fort/FortType.proto\x1a\x1aMap/Fort/FortSponsor.proto\x1a Map/Fort/FortRenderingType.proto\x1a\x1bMap/Fort/FortLureInfo.proto\"\xbb\x04\n\x08\x46ortData\x12\n\n\x02id\x18\x01 \x01(\t\x12\"\n\x1alast_modified_timestamp_ms\x18\x02 \x01(\x03\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x12\x0f\n\x07\x65nabled\x18\x08 \x01(\x08\x12+\n\x04type\x18\t \x01(\x0e\x32\x1d.POGOProtos.Map.Fort.FortType\x12\x32\n\rowned_by_team\x18\x05 \x01(\x0e\x32\x1b.POGOProtos.Enums.TeamColor\x12\x35\n\x10guard_pokemon_id\x18\x06 \x01(\x0e\x32\x1b.POGOProtos.Enums.PokemonId\x12\x18\n\x10guard_pokemon_cp\x18\x07 \x01(\x05\x12\x12\n\ngym_points\x18\n \x01(\x03\x12\x14\n\x0cis_in_battle\x18\x0b \x01(\x08\x12&\n\x1e\x63ooldown_complete_timestamp_ms\x18\x0e \x01(\x03\x12\x31\n\x07sponsor\x18\x0f \x01(\x0e\x32 .POGOProtos.Map.Fort.FortSponsor\x12>\n\x0erendering_type\x18\x10 \x01(\x0e\x32&.POGOProtos.Map.Fort.FortRenderingType\x12\x1c\n\x14\x61\x63tive_fort_modifier\x18\x0c \x01(\x0c\x12\x34\n\tlure_info\x18\r \x01(\x0b\x32!.POGOProtos.Map.Fort.FortLureInfoP\x00P\x01P\x02P\x03P\x04P\x05\x62\x06proto3')
  ,
  dependencies=[Enums_dot_PokemonId__pb2.DESCRIPTOR,Enums_dot_TeamColor__pb2.DESCRIPTOR,Map_dot_Fort_dot_FortType__pb2.DESCRIPTOR,Map_dot_Fort_dot_FortSponsor__pb2.DESCRIPTOR,Map_dot_Fort_dot_FortRenderingType__pb2.DESCRIPTOR,Map_dot_Fort_dot_FortLureInfo__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FORTDATA = _descriptor.Descriptor(
  name='FortData',
  full_name='POGOProtos.Map.Fort.FortData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='POGOProtos.Map.Fort.FortData.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_modified_timestamp_ms', full_name='POGOProtos.Map.Fort.FortData.last_modified_timestamp_ms', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='POGOProtos.Map.Fort.FortData.latitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='POGOProtos.Map.Fort.FortData.longitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='POGOProtos.Map.Fort.FortData.enabled', index=4,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='POGOProtos.Map.Fort.FortData.type', index=5,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owned_by_team', full_name='POGOProtos.Map.Fort.FortData.owned_by_team', index=6,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='guard_pokemon_id', full_name='POGOProtos.Map.Fort.FortData.guard_pokemon_id', index=7,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='guard_pokemon_cp', full_name='POGOProtos.Map.Fort.FortData.guard_pokemon_cp', index=8,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gym_points', full_name='POGOProtos.Map.Fort.FortData.gym_points', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_in_battle', full_name='POGOProtos.Map.Fort.FortData.is_in_battle', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cooldown_complete_timestamp_ms', full_name='POGOProtos.Map.Fort.FortData.cooldown_complete_timestamp_ms', index=11,
      number=14, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sponsor', full_name='POGOProtos.Map.Fort.FortData.sponsor', index=12,
      number=15, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rendering_type', full_name='POGOProtos.Map.Fort.FortData.rendering_type', index=13,
      number=16, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='active_fort_modifier', full_name='POGOProtos.Map.Fort.FortData.active_fort_modifier', index=14,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lure_info', full_name='POGOProtos.Map.Fort.FortData.lure_info', index=15,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=782,
)

_FORTDATA.fields_by_name['type'].enum_type = Map_dot_Fort_dot_FortType__pb2._FORTTYPE
_FORTDATA.fields_by_name['owned_by_team'].enum_type = Enums_dot_TeamColor__pb2._TEAMCOLOR
_FORTDATA.fields_by_name['guard_pokemon_id'].enum_type = Enums_dot_PokemonId__pb2._POKEMONID
_FORTDATA.fields_by_name['sponsor'].enum_type = Map_dot_Fort_dot_FortSponsor__pb2._FORTSPONSOR
_FORTDATA.fields_by_name['rendering_type'].enum_type = Map_dot_Fort_dot_FortRenderingType__pb2._FORTRENDERINGTYPE
_FORTDATA.fields_by_name['lure_info'].message_type = Map_dot_Fort_dot_FortLureInfo__pb2._FORTLUREINFO
DESCRIPTOR.message_types_by_name['FortData'] = _FORTDATA

FortData = _reflection.GeneratedProtocolMessageType('FortData', (_message.Message,), dict(
  DESCRIPTOR = _FORTDATA,
  __module__ = 'Map.Fort.FortData_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Map.Fort.FortData)
  ))
_sym_db.RegisterMessage(FortData)


# @@protoc_insertion_point(module_scope)
