# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Settings/Master/TypeEffectiveSettings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Enums import BadgeType_pb2 as Enums_dot_BadgeType__pb2
from Enums import PokemonType_pb2 as Enums_dot_PokemonType__pb2

from Enums.BadgeType_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Settings/Master/TypeEffectiveSettings.proto',
  package='POGOProtos.Settings.Master',
  syntax='proto3',
  serialized_pb=_b('\n+Settings/Master/TypeEffectiveSettings.proto\x12\x1aPOGOProtos.Settings.Master\x1a\x15\x45nums/BadgeType.proto\x1a\x17\x45nums/PokemonType.proto\"b\n\x15TypeEffectiveSettings\x12\x15\n\rattack_scalar\x18\x01 \x03(\x02\x12\x32\n\x0b\x61ttack_type\x18\x02 \x01(\x0e\x32\x1d.POGOProtos.Enums.PokemonTypeP\x00\x62\x06proto3')
  ,
  dependencies=[Enums_dot_BadgeType__pb2.DESCRIPTOR,Enums_dot_PokemonType__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TYPEEFFECTIVESETTINGS = _descriptor.Descriptor(
  name='TypeEffectiveSettings',
  full_name='POGOProtos.Settings.Master.TypeEffectiveSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attack_scalar', full_name='POGOProtos.Settings.Master.TypeEffectiveSettings.attack_scalar', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack_type', full_name='POGOProtos.Settings.Master.TypeEffectiveSettings.attack_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=221,
)

_TYPEEFFECTIVESETTINGS.fields_by_name['attack_type'].enum_type = Enums_dot_PokemonType__pb2._POKEMONTYPE
DESCRIPTOR.message_types_by_name['TypeEffectiveSettings'] = _TYPEEFFECTIVESETTINGS

TypeEffectiveSettings = _reflection.GeneratedProtocolMessageType('TypeEffectiveSettings', (_message.Message,), dict(
  DESCRIPTOR = _TYPEEFFECTIVESETTINGS,
  __module__ = 'Settings.Master.TypeEffectiveSettings_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Settings.Master.TypeEffectiveSettings)
  ))
_sym_db.RegisterMessage(TypeEffectiveSettings)


# @@protoc_insertion_point(module_scope)
