# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Networking/Requests/Messages/SetAvatarMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Data.Player import PlayerAvatar_pb2 as Data_dot_Player_dot_PlayerAvatar__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Networking/Requests/Messages/SetAvatarMessage.proto',
  package='POGOProtos.Networking.Requests.Messages',
  syntax='proto3',
  serialized_pb=_b('\n3Networking/Requests/Messages/SetAvatarMessage.proto\x12\'POGOProtos.Networking.Requests.Messages\x1a\x1e\x44\x61ta/Player/PlayerAvatar.proto\"O\n\x10SetAvatarMessage\x12;\n\rplayer_avatar\x18\x02 \x01(\x0b\x32$.POGOProtos.Data.Player.PlayerAvatarb\x06proto3')
  ,
  dependencies=[Data_dot_Player_dot_PlayerAvatar__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SETAVATARMESSAGE = _descriptor.Descriptor(
  name='SetAvatarMessage',
  full_name='POGOProtos.Networking.Requests.Messages.SetAvatarMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_avatar', full_name='POGOProtos.Networking.Requests.Messages.SetAvatarMessage.player_avatar', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=207,
)

_SETAVATARMESSAGE.fields_by_name['player_avatar'].message_type = Data_dot_Player_dot_PlayerAvatar__pb2._PLAYERAVATAR
DESCRIPTOR.message_types_by_name['SetAvatarMessage'] = _SETAVATARMESSAGE

SetAvatarMessage = _reflection.GeneratedProtocolMessageType('SetAvatarMessage', (_message.Message,), dict(
  DESCRIPTOR = _SETAVATARMESSAGE,
  __module__ = 'Networking.Requests.Messages.SetAvatarMessage_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Requests.Messages.SetAvatarMessage)
  ))
_sym_db.RegisterMessage(SetAvatarMessage)


# @@protoc_insertion_point(module_scope)
