# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Networking/Requests/Messages/SetPlayerTeamMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Enums import TeamColor_pb2 as Enums_dot_TeamColor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Networking/Requests/Messages/SetPlayerTeamMessage.proto',
  package='POGOProtos.Networking.Requests.Messages',
  syntax='proto3',
  serialized_pb=_b('\n7Networking/Requests/Messages/SetPlayerTeamMessage.proto\x12\'POGOProtos.Networking.Requests.Messages\x1a\x15\x45nums/TeamColor.proto\"A\n\x14SetPlayerTeamMessage\x12)\n\x04team\x18\x01 \x01(\x0e\x32\x1b.POGOProtos.Enums.TeamColorb\x06proto3')
  ,
  dependencies=[Enums_dot_TeamColor__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SETPLAYERTEAMMESSAGE = _descriptor.Descriptor(
  name='SetPlayerTeamMessage',
  full_name='POGOProtos.Networking.Requests.Messages.SetPlayerTeamMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='team', full_name='POGOProtos.Networking.Requests.Messages.SetPlayerTeamMessage.team', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=188,
)

_SETPLAYERTEAMMESSAGE.fields_by_name['team'].enum_type = Enums_dot_TeamColor__pb2._TEAMCOLOR
DESCRIPTOR.message_types_by_name['SetPlayerTeamMessage'] = _SETPLAYERTEAMMESSAGE

SetPlayerTeamMessage = _reflection.GeneratedProtocolMessageType('SetPlayerTeamMessage', (_message.Message,), dict(
  DESCRIPTOR = _SETPLAYERTEAMMESSAGE,
  __module__ = 'Networking.Requests.Messages.SetPlayerTeamMessage_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Requests.Messages.SetPlayerTeamMessage)
  ))
_sym_db.RegisterMessage(SetPlayerTeamMessage)


# @@protoc_insertion_point(module_scope)
