# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Inventory/Item.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Inventory import ItemId_pb2 as Inventory_dot_ItemId__pb2

from Inventory.ItemId_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Inventory/Item.proto',
  package='POGOProtos.Inventory',
  syntax='proto3',
  serialized_pb=_b('\n\x14Inventory/Item.proto\x12\x14POGOProtos.Inventory\x1a\x16Inventory/ItemId.proto\"T\n\x04Item\x12-\n\x07item_id\x18\x01 \x01(\x0e\x32\x1c.POGOProtos.Inventory.ItemId\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x0e\n\x06unseen\x18\x03 \x01(\x08P\x00\x62\x06proto3')
  ,
  dependencies=[Inventory_dot_ItemId__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='POGOProtos.Inventory.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='POGOProtos.Inventory.Item.item_id', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='POGOProtos.Inventory.Item.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unseen', full_name='POGOProtos.Inventory.Item.unseen', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=154,
)

_ITEM.fields_by_name['item_id'].enum_type = Inventory_dot_ItemId__pb2._ITEMID
DESCRIPTOR.message_types_by_name['Item'] = _ITEM

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'Inventory.Item_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Inventory.Item)
  ))
_sym_db.RegisterMessage(Item)


# @@protoc_insertion_point(module_scope)
