# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/ItemAward.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from POGOProtos.Inventory import ItemId_pb2 as POGOProtos_dot_Inventory_dot_ItemId__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Inventory/ItemAward.proto',
  package='POGOProtos.Inventory',
  syntax='proto3',
  serialized_pb=_b('\n$POGOProtos/Inventory/ItemAward.proto\x12\x14POGOProtos.Inventory\x1a!POGOProtos/Inventory/ItemId.proto\"N\n\tItemAward\x12-\n\x07item_id\x18\x01 \x01(\x0e\x32\x1c.POGOProtos.Inventory.ItemId\x12\x12\n\nitem_count\x18\x02 \x01(\x05\x62\x06proto3')
  ,
  dependencies=[POGOProtos_dot_Inventory_dot_ItemId__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ITEMAWARD = _descriptor.Descriptor(
  name='ItemAward',
  full_name='POGOProtos.Inventory.ItemAward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='POGOProtos.Inventory.ItemAward.item_id', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_count', full_name='POGOProtos.Inventory.ItemAward.item_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=175,
)

_ITEMAWARD.fields_by_name['item_id'].enum_type = POGOProtos_dot_Inventory_dot_ItemId__pb2._ITEMID
DESCRIPTOR.message_types_by_name['ItemAward'] = _ITEMAWARD

ItemAward = _reflection.GeneratedProtocolMessageType('ItemAward', (_message.Message,), dict(
  DESCRIPTOR = _ITEMAWARD,
  __module__ = 'POGOProtos.Inventory.ItemAward_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Inventory.ItemAward)
  ))
_sym_db.RegisterMessage(ItemAward)


# @@protoc_insertion_point(module_scope)
